name: run-tests

on:
  push:
    branches:
      - master
    pull_request:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install Dependencies
              run: npm ci

            - name: Prepare Nuxt
              run: npx nuxi prepare

            - name: Run Tests
              run: npx vitest run
