name: run-tests

on:
    push:
    pull_request:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install Dependencies
              run: npm ci

            - name: Run Unit Tests
              run: npx vitest run

            - name: Install Playwright Browsers
              run: npx playwright install chromium --with-deps

            - name: Run E2E Tests
              run: npx playwright test
